
server:
  port: 10001
spring:
  application:
    name: micro-dyu-cms
#  cloud:
#    stream:
#      bindings:
#        modify-in:
#          destination: dyu.test1.exchange
#        modify-out:
#          destination: dyu.test1.exchange
#          content-type: text/plain
#      default-binder: rabbit
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka
