server:
  port: 8888
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.8.230:3306/links86
#    username: root
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#  redis:
#    host: 192.168.8.230
#  data:
#    elasticsearch:
logging:
  level: debug
#      cluster-nodes: 192.168.8.230